### ISSUE TITLE
新增临时素材时的疑问!

### ISSUE THREAD

**Issue by minkoonim** [offu/WeRoBot#290]
## 1. 我想要 ...

  - [x] 反馈 BUG
  - [ ] 提出新的需求
  
  
## 2. WeRoBot 的行为是？

  * **当前行为:**
新增临时素材时,
1) upload_media('image', './docs/test.jpg')
-> invalid file type

2) f = open(image[i],'rb')
upload_media('image', f)
-> data missing

3)upload_media('image', f.read())
-> invalid file type ..again

  * **应有行为:**
好想要get一个正常的mediaID结果.. 
看了werobot文档, 微信公众平台文档, 百度了, 谷歌了, 哭了笑了都没用

## 3. 复现方式:

  * WeRoBot 版本: ```**1.4.0**```
  * 平台: ```Windows/**Linux**/macOS```
  * Python 版本: ```**3.6**```
  * 复现代码:
  ``` python
  print("代码区")
  ```

**Comment by whtsky** [comment]
用法相关的问题请在 SegmentFault 社区或者在 QQ 群进行讨论
