### ISSUE TITLE
error in ｗｅｒｏｂｏｔ when send voice message

### ISSUE THREAD

**Issue by lucky-ing** [offu/WeRoBot#299]
when send a voice type message, it always come out a error that as "40005 invalid file type hint."

**Comment by whtsky** [comment]
> Issue tracker 只用于反馈 bug 和 feature request。
> 在提问前请仔细阅读我们的文档，并推荐阅读《提问的智慧》：
> https://github.com/ruby-china/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md
