### ISSUE TITLE
奇怪

### ISSUE THREAD

**Issue by smartweare** [offu/WeRoBot#302]
AttributeError: module 'werobot' has no attribute 'WeRoBot'

**Comment by helloqiu** [comment]
> Issue tracker 只用于反馈 bug 和 feature request。
与 WeRoBot 用法相关的问题请加入主页上的 QQ 群讨论或在 SegmentFault 社区提问。
在提问前请仔细阅读我们的文档，并推荐阅读《提问的智慧》：
https://github.com/ruby-china/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md
如果反馈 bug 请参考模板并提供复现
