### ISSUE TITLE
启动时pymysql提示table already exist

### ISSUE THREAD

**Issue by Creedowl** [offu/WeRoBot#372]
* **对 Bug 的描述**
  * 当前行为：我使用mysql存储session，用pymysql连接，每次启动的时候会提示
```
/Users/creedowl/PycharmProjects/nuaa_bot/venv/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1050, "Table 'WeRoBot' already exists")
  result = self._query(query)
```
  * 正确的行为：正常启动

* **环境**
  * 平台：mac
  * WeRoBot 版本号：最新
  * Python 版本：3.7

* **复现代码或 repo 链接**

```python
官方示例

# 请在这里给出 bug 的复现代码。如有必要，可以创建一个复现 repo 并将链接粘贴到这里。
```

* **复现步骤**

* **其他信息**

**Comment by whtsky** [comment]
MySQL 版本是？

**Comment by Creedowl** [comment]
@whtsky 用docker部署的应该是8，明天我确认一下

**Comment by whtsky** [comment]
看起来这是 MySQL 的 feature
/cc @helloqiu 要考虑换成没有 warning 的实现方式吗

**Comment by helloqiu** [comment]
> 要考虑换成没有 warning 的实现方式吗

出现一个 warning 有什么副作用吗？如果没有我觉得现在的 `CREATE TABLE IF NOT EXISTS` 也能接受？ @whtsky

**Comment by Creedowl** [comment]
@helloqiu 强迫症觉得很难受。。而且这个是正常情况不应该是warning吧

**Comment by whtsky** [comment]
我觉得可以接受

**Comment by whtsky** [comment]
显示 warning 是 MySQL 的行为，想了一下觉得现在的实现没什么问题。 当然欢迎你 PR 换成不使用 `CREATE TABLE IF NOT EXISTS` 的方式
