### ISSUE TITLE
文档中存在错别字

### ISSUE THREAD

**Issue by rikiesxiao** [offu/WeRoBot#375]
* **对 Bug 的描述**
  * 当前行为：WeRoBot 会**讲**消息转交给 Handler 进行处理，并将 Handler 的返回值返回给微信服务器
[https://werobot.readthedocs.io/zh_CN/latest/start.html
](https://werobot.readthedocs.io/zh_CN/latest/start.html)
  * 正确的行为：会**将**消息转交给 Handler 进行处理

* **环境**
  * 平台：不相关
  * WeRoBot 版本号：1.6.0
  * Python 版本：不相关

* **复现代码或 repo 链接**
不相关
* **复现步骤**
打开[文档](https://werobot.readthedocs.io/zh_CN/latest/)康康

* **其他信息**
无

**Comment by whtsky** [comment]
fixed, thanks
