### ISSUE TITLE
发送特定纯文本消息失败

### ISSUE THREAD

**Issue by Tiande** [offu/WeRoBot#388]
* **对 Bug 的描述**
  * 当前行为：用户端提示 "该公众号提供的服务出现故障，请稍后再试"，服务端无 bug log
  * 正确的行为：用户端应显示指定文本消息
  * 同类型的其他行为：用户端显示正常

* **环境**
  * 平台：Debian
  * WeRoBot 版本号：1.6.0
  * Python 版本：2.7.13

* **复现代码或 repo 链接**

```python
from werobot import WeRoBot

...

    # 这里的 message 已转为 message.content 对象
    if message.startswith(("-介")) and len(message.split()) > 1:
        myContent = message.split()[1]
        return  housql.getIntros(myContent) # 返回一串纯文本信息，且正常使用

...

```

* **复现步骤**
用户回复，触发查询

* **其他信息**
1. 尝试了更多字数的返回，正常。 
2. 怀疑是否有敏感词检测，但是无果。 
3. 以下为失败消息的整体内容：

> 「英雄的追随者」
从异世界神居古潭而来的，没有召唤主的「转光生」兽人。喜爱名为人类的种族，为了寻找能传授自身武学并侍奉其身的拥有英雄资质的人类，将自己置身于强者汇集的池袋公会的神居之狼。侍奉君主，将其培育成英雄，并时常抱持着总有一天自己将成为英雄的剑与盾为英雄而死的觉悟。在战场上以一名严师的身份培育着英雄，在日常生活当中则是一名极度溺爱召唤主的颓废人类製造机。对喜欢照顾别人，或是喜欢家事的对象很聊得来。
「险峻冰壁」
于战场上，身穿释放着寒气的手甲与护脚的神器，战斗时以突进与踢击的格斗技为主。腰间所配戴的，是有着狼神工艺的弯刀神器，他认为这把神器必须是要奉献给英雄或是人类的主人而暂时放在自己身上的物品。比起住在有着各种神灵的世界裡他更期望着能住在有着众多人类的地上而被召唤至此处。由于对这个世界的常识还不是很足够的关係，有着不通世俗的一面，能很自然的说出对君主的忠诚与敬爱。面对站在与英雄相对位子的人，或是将其他人的侍奉觉得理所当然的傲慢的支配者则会明确的与其保持距离。
额外补足：阿伊努神话中的狩猎之神，名子中的ホロケウ就是狼的意思，而设定中的异界神居古潭位于日本的北海道距离旭川市仅只有三十分钟的车程，另外就是不知道为甚麽整个放课后中的角色唯独神威受到欧美那边的青睐，还有就是神威根本就没穿对吧。
「击碎冰壁的白刃」
365天24小时，他都希望能跟英雄同在，并强烈的希望英雄能够依靠著他。那是因为他所选上的最后一位英雄，独自的离他远去到他的手所无法触及的地方，而他心中的伤痕正是那愿望的起因。等有一天，他不用再背负那「职责」时，或许他才能够展现出真正的自己也说不定。绑在神威腰间的，是他所培育的最后的英雄所该持有的「神器」。第23.....不对，是第24位英雄的刀刃，那斩击连冻星都能一刀斩断。而他正是寄宿于那把刀的刀拵上，守护著持有主的狼。
额外补足：于主线第七章新增的五星神威，全游戏中第一位英雄属性的角色。

**Comment by helloqiu** [comment]
> 尝试了更多字数的返回，正常。  

记得微信有 text 长度不超过 2048 字节的限制？  
试了试用 `Client.send_text_message` 去发送这条消息，收到的错误是：
```
werobot.client.ClientException: 45002: content size out of limit hint: [rtm5JA0874shc2]
```
所以应该是超长了。
