### ISSUE TITLE
内容含有xc字符时会出现公众号故障

### ISSUE THREAD

**Issue by zhanghsgithub** [offu/WeRoBot#419]
发送的字符串服务器收到的信息为
`
<xml>  <ToUserName><![CDATA[gh_***]]></ToUserName>\n   
 <FromUserName><![CDATA[opid***]]></FromUserName>\n 
    <CreateTime>1551481349</CreateTime>\n  
      <MsgType><![CDATA[text]]></MsgType>\n   
       <Content><![CDATA[ \x1dc]]></Content>\n  
         <MsgId>22211872600753510</MsgId>\n 
            <Encrypt><![CDATA[***]]></Encrypt>\n
            </xml>
`
发送该内容后，无法解析这个xml

**Comment by helloqiu** [comment]
> 请注意：不规范的问题会被部署的 issue bot 自动关闭。
