### ISSUE TITLE
windows python3.6 运行报错

### ISSUE THREAD

**Issue by ijustlearn** [offu/WeRoBot#450]
* **对 Bug 的描述**
  * 当前行为：
Traceback (most recent call last):
  File "E:/pycharmWorkSpace/my-wxrobot/werobot.py", line 1, in <module>
    import werobot
  File "E:\pycharmWorkSpace\my-wxrobot\werobot.py", line 4, in <module>
    robot = werobot.WeRoBot(token='tokenhere')
AttributeError: module 'werobot' has no attribute 'WeRoBot'
  * 正确的行为：
正常启动

* **环境**
  * 平台： windows10 64位
  * WeRoBot 版本号：WeRoBot==1.9.0
  * Python 版本：Python 3.6.3
 使用pycharm开发
* **复现代码或 repo 链接**
werobot.py :
import werobot
robot = werobot.WeRoBot(token='tokenhere')
@robot.text
def hello_world():
    return 'Hello World!'
robot.run()

* **复现步骤**

python werobot.py

* **其他信息**
是不支持3.6.3么？

**Comment by helloqiu** [comment]
建议尝试换个不叫 `werobot.py` 的文件名

**Comment by ijustlearn** [comment]
可以了，谢谢~
