### ISSUE TITLE
重启nginx服务后，无法正常代理Werobot

### ISSUE THREAD

**Issue by TAOYi92** [offu/WeRoBot#456]
* **对 Bug 的描述**
  * 当前行为：重启nginx服务后，无法正常代理Werobot。证据：访问`http://<ip地址>/WX/`是404. （不是`/`的问题）。想知道大家的服务还可以正常用吗？
  * 正确的行为：可以显示正确的成功网页。（注意：之前我已经成功使用3个月了）

* **环境**
  * 平台：CentOS7
  * WeRoBot 版本号: 1.9.0
  * Python 版本：3.6.7

* **复现代码或 repo 链接**

```python
from werobot import WeRoBot

# 请在这里给出 bug 的复现代码。如有必要，可以创建一个复现 repo 并将链接粘贴到这里。
```

* **复现步骤**
```
$ sudo systemctl restart nginx
$ sudo systemctl restart WX
```
* **其他信息**

**Comment by whtsky** [comment]
Issue 只用于反馈 bug 和 feature request。
