### ISSUE TITLE
WeRobot生成图片并回复，超过5秒返回公众号异常

### ISSUE THREAD

**Issue by ShellMonster** [offu/WeRoBot#485]
* **对 Bug 的描述**
  * 当前行为：WeRobot处理消息，生成图片后返回给用户，上传素材ID已成功，但需要返回时已超过5s，服务端会重新发起请求，但用户端显示公众号异常，无法正常收到图片；(使用return回复success后，无法继续执行后续代码)
  * 正确的行为：求一个SuccessReply回复的Demo或者当前的其他解决方案，谢谢(查了issue历史没有找到解决的方案。)

* **环境**
  * 平台：Centos 7.4 64位
  * WeRoBot 版本号：1.9.0
  * Python 版本：3.7.3

* **复现代码或 repo 链接**

```python
from werobot import WeRoBot
from werobot.replies import ImageReply, SuccessReply

@robot.text  # 消息检测回复
def get_data(msg):
    #此处省去了生成图片的代码未展示；
    media_id = client.upload_permanent_media("image", open(r"./gaoding_new.png", "rb"))['media_id']
    return ImageReply(message=msg, media_id=media_id)

# 请在这里给出 bug 的复现代码。如有必要，可以创建一个复现 repo 并将链接粘贴到这里。
```

* **复现步骤**

* **其他信息**

**Comment by whtsky** [comment]
Issue tracker 只用于反馈 bug 和 feature request。
