### ISSUE TITLE
无法获取图片消息中的media_id并进行相应回复

### ISSUE THREAD

**Issue by devshilei** [offu/WeRoBot#495]
* **对 Bug 的描述**
  * 当前行为：接收图片消息，返回不了相同图片，只能获取图片连接。
  * 正确的行为：接收图片消息可以返回相同图片。

* **环境**
  * 平台：ubuntu 16.04
  * WeRoBot 版本号：1.9.0
  * Python 版本：3.5.2

* **复现代码或 repo 链接**

```python
from werobot import WeRoBot
@robot.image
def img(message):
    # 将接收的图片链接返回给用户
    return message.img

# 请在这里给出 bug 的复现代码。如有必要，可以创建一个复现 repo 并将链接粘贴到这里。
```python
from werobot import WeRoBot
@robot.image
def img(message):
    # 将接收的图片链接返回给用户
    return message.img

* **复现步骤**

# @robot.image 修饰的处理图片消息
@robot.image
def img(message):
    # 将接收的图片链接返回给用户
    return message.img


* **其他信息**
<!-- 如对 bug 修复的建议、相关 issue 或 PR 的引用等信息 -->
希望可以通过Reply模块或者某个字段直接返回接收的图片。

**Comment by whtsky** [comment]
微信平台设计如此，无能为力

**Comment by devshilei** [comment]
请查看当前微信官方文档，中间包含了图片消息参数的详细说明，其中包含media_id，可以通过该字段获取图片内容，然后可以通过ImageReply回复图片内容。本人以经通过修改代码在服务器上试过了。
# @robot.image 修饰图片消息
@robot.image
def img(message):
    # 将接收的图片发送给用户
    media_id = message.media_id
    reply = ImageReply(message=message, media_id=media_id)
    return reply

**Comment by whtsky** [comment]
竟然支持了

**Comment by devshilei** [comment]
^_^，求加入小伙伴，代码审核已提交。
