### ISSUE TITLE
对于Message Event=templatesendjobfinish 的处理

### ISSUE THREAD

**Issue by mywaiting** [offu/WeRoBot#541]
* **遇到的问题**

因为自己的项目需要用到 微信公众号（服务号）的模板信息发送，需要在微信回调中处理 Message Event=templatesendjobfinish 类型的信息，我翻看 WeRoBot.messages.events 里面已经有 Event = templatesendjobfinish 相关实现，为什么不整理好放入 werobot.robot 里面，然后整理成 装饰器？

* **解决方案**

如果仓库管理者觉得可以引入 PR 的话

我已经完整整理好 Message Event=templatesendjobfinish  处理的相关代码，等这个 issue 的回复，然后 fork 并 PR 代码

* **其他内容**

暂无~

**Comment by whtsky** [comment]
咦，感觉是漏了……

这种问题直接发 PR 就好，不需要征求 maintainer 的意见。
我觉得比较好的处理方式是 `BaseRoBot` 的 `message_types` 直接在 `WeRoBotMetaClass.TYPES`  的基础上进行构造。

**Comment by mywaiting** [comment]
> 
> 
> 咦，感觉是漏了……
> 
> 这种问题直接发 PR 就好，不需要征求 maintainer 的意见。
> 我觉得比较好的处理方式是 `BaseRoBot` 的 `message_types` 直接在 `WeRoBotMetaClass.TYPES` 的基础上进行构造。

我翻了一下代码也觉得这里写得很诡异，明明 `werobot.messages.events ` 里面都写了，为什么 `BaseRoBot.message_types` 不顺手加一下

反正都写了 `werobot.messages.base.WeRoBotMetaClass` 这个 metaclass，的确是抽取这里的 `WeRoBotMetaClass.TYPES` 到 `BaseRoBot.message_types` 是最简洁的实现

这两天忙，如果这两天你们没空加的话，我迟点 PR 一个给你们加上~

顺便说 `BaseRoBot` 里面一堆 `self.add_handler(f, type='xxx');` 这样的方便用于装饰器调用的方法，其实遍历一下  `WeRoBotMetaClass.TYPES` 写入到 `self` 增加方法即可，这样每个都写一次，很容易遗漏的

**Comment by whtsky** [comment]
是的，我也觉得很诡异…… 不知道当时自己脑子里都在想啥

那我等 PR 啦

**Comment by mywaiting** [comment]
things done!

**Comment by whtsky** [comment]
https://github.com/offu/WeRoBot/releases/tag/v1.12.0
