### ISSUE TITLE
AttributeError: 'module' object has no attribute 'WeRoBot'

### ISSUE THREAD

**Issue by yishangfei** [offu/WeRoBot#567]
* **对 Bug 的描述**
  * 当前行为：
  * 正确的行为：

* **环境**
  * 平台：Debian GNU/Linux 9 
  * WeRoBot 版本号：1.12.0
  * Python 版本：python3.6

* **复现代码或 repo 链接**

```python
from werobot import WeRoBot

# 请在这里给出 bug 的复现代码。如有必要，可以创建一个复现 repo 并将链接粘贴到这里。
```
![image](https://user-images.githubusercontent.com/15099278/82547739-ca4d1f00-9b8c-11ea-9c02-5969550d7f35.png)
![image](https://user-images.githubusercontent.com/15099278/82547754-d20cc380-9b8c-11ea-9412-30b3e8c31ba8.png)

* **复现步骤**

* **其他信息**

**Comment by whtsky** [comment]
https://github.com/offu/WeRoBot/issues/175#issuecomment-418811321

**Comment by yishangfei** [comment]
![image](https://user-images.githubusercontent.com/15099278/82558779-fb374f00-9ba0-11ea-8be7-ac7b36468fe0.png)
@whtsky 运行 pip install funcsigs  无用  名字也不是werobot.py

**Comment by yishangfei** [comment]
![image](https://user-images.githubusercontent.com/15099278/82559262-e1e2d280-9ba1-11ea-81d3-6658176f9fdd.png)
红框使用python3 直接使用包
橙框from werobot.robot import WeRoBot 导入进行运行的效果

**Comment by yishangfei** [comment]
要用python3 文件名.py 运行

**Comment by zoeymeng913** [comment]
还是不行一样是 module 'werobot' has no attribute 'WeRoBot'
