### ISSUE TITLE
如何手动重写get_access_token函数来自定义token的存储

### ISSUE THREAD

**Issue by wanghaiqing2015** [offu/WeRoBot#620]
* **对 Bug 的描述**
  * 当前行为：能否给一个参考用例，重写get_access_token函数来自定义token的存储
  * 正确的行为：重写get_access_token函数来自定义token的存储

* **环境**
  * 平台：Windows
  * WeRoBot 版本号：1.3.0
  * Python 版本：3.6

* **复现代码或 repo 链接**

```python
from werobot import WeRoBot

get_access_token()

```

* **复现步骤**

* **其他信息**

**Comment by wanghaiqing2015** [comment]
已经解决

**Comment by whtsky** [comment]
Issue tracker 只用于反馈 bug 和 feature request 。

**Comment by wanghaiqing2015** [comment]
已经实现！！！！

**Comment by jcevo** [comment]
> 已经实现！！！！

@wanghaiqing2015 您好，请问怎么实现的？

**Comment by Leweibo** [comment]
我的实现方式，目前正常，还在等待继续测试。
   

def get_access_token(self):        
        data = { 
            "grant_type": "client_credential",
            "appid": "",
            "secret": ""
        }
        r = requests.post(url="https://api.weixin.qq.com/cgi-bin/stable_token", json=data)
        r.encoding = "utf-8"
        json = r.json()
        print(json)
        self._token = json["access_token"]
        self.token_expires_at = int(time.time()) + json["expires_in"]
        return self._token
