### ISSUE TITLE
语法错误def to_text(value, encoding="utf-8") -> str: 

### ISSUE THREAD

**Issue by liukefu2050** [offu/WeRoBot#625]
* **对 Bug 的描述**
  * 当前行为：代码werobot/utils.py
  * 正确的行为：编译时报错

* **环境**
  * 平台：linux
  * WeRoBot 版本号：最新
  * Python 版本：3.9.0

* **复现代码或 repo 链接**

```python
from werobot import WeRoBot

# 请在这里给出 bug 的复现代码。如有必要，可以创建一个复现 repo 并将链接粘贴到这里。
```

* **复现步骤**

* **其他信息**
 无

**Comment by helloqiu** [comment]
@liukefu2050 麻烦提供一下复现的代码？这部分单元测试在 3.9 的环境上都跑过了：
`latest master unit tests results`: https://github.com/offu/WeRoBot/runs/1767178407?check_suite_focus=true#step:7:233
`latest master unit tests`: https://github.com/offu/WeRoBot/blob/f5a011398504884d423c4e973755e329a5c00953/tests/test_utils.py#L15
