### ISSUE TITLE
使用WeRoBot新增永久素材成功，怎么群发？

### ISSUE THREAD

**Issue by kemistep** [offu/WeRoBot#634]
* **遇到的问题**

* **解决方案**

* **其他内容**

```python 
  news_json = client.add_news(articles)
  print(news_json)  news_json = client.add_news(articles)
{'media_id': 'yJCW-Z_VZwPZtLOTqcSltMrBQDpVkrRfX8O4LvR-Oc0', 'item': []}
````
已经成功获取到：media_id

但是现在想每日群发一篇公众号内容，但是找不到方法；

查看文档：
有群发接口，但是群发的内容是content，不是media_id，这个又要重新获取一遍内容嘛；
![image](https://user-images.githubusercontent.com/16223610/108950506-4e46b100-76a1-11eb-87ef-d71abb1f3eed.png)

问题：
如果推送上传永久素材的文章；

**Comment by kemistep** [comment]
文档有解决办法：Client.send_news_message

**Comment by OHeroJ** [comment]
> 文档有解决办法：Client.send_news_message

请问这个接口，能实现订阅号每日发文么？

**Comment by kemistep** [comment]
> > 文档有解决办法：Client.send_news_message
> 
> 请问这个接口，能实现订阅号每日发文么？

这个需要权限支持，个人公众号没有这个权限的，实现不了；
