### ISSUE TITLE
回复图文时，图文消息中的图片卡不显示

### ISSUE THREAD

**Issue by matthuo333** [offu/WeRoBot#711]
* **对 Bug 的描述**
  * 当前行为：利用text装饰器，在一个列表中返回四个元素，均按照规范返回。但是其中图片不能显示。
  * 正确的行为：图片正常显示

* **环境**
  * 平台：Ubuntu20.14
  * WeRoBot 版本号：1.13.1
  * Python 版本：3.9.7

* **复现代码或 repo 链接**
* @robot.text
def articles(message):

        res = GetContent.getContent(message.content)

        if res == "This is a 1.4.2 Article" :

            return [
 
                [
                    "xxx官方会员套餐",
                    "xxx Membership Plan",
                    "https://mp.weixin.qq.com/s?__biz=MzIyMTk2ODc3Mw==&mid=2247487824&idx=1&sn=6a5f13fbd70d07fc843518195394d65a&chksm=e835f1badf4278ac412752d7f261b0cca691e854a90557546d510082bd6a711ee2670f74fa0a#rd",
                    "https://mp.weixin.qq.com/s/xxxx"
                ]
            ]
        else :
           return res

```python
from werobot import WeRoBot

# 请在这里给出 bug 的复现代码。如有必要，可以创建一个复现 repo 并将链接粘贴到这里。
```

* **复现步骤**

* **其他信息**

**Comment by helloqiu** [comment]
建议使用 [ArticleReply](https://werobot.readthedocs.io/zh_CN/latest/replies.html#articlesreply)
