### ISSUE TITLE
请问如何与FastAPI结合使用

### ISSUE THREAD

**Issue by xiaoqiangclub** [offu/WeRoBot#726]
* **对 Bug 的描述**
  * 当前行为：
  * 正确的行为：

* **环境**
  * 平台：
  * WeRoBot 版本号：
  * Python 版本：

* **复现代码或 repo 链接**

```python
from werobot import WeRoBot

# 请在这里给出 bug 的复现代码。如有必要，可以创建一个复现 repo 并将链接粘贴到这里。
```

* **复现步骤**

* **其他信息**

**Comment by whtsky** [comment]
Close in favor of #727
