### ISSUE TITLE
建议添加与FastAPI结合部署的接口

### ISSUE THREAD

**Issue by xiaoqiangclub** [offu/WeRoBot#727]
* **遇到的问题**

    - 当前Python很多人都在使用FastAPI， 希望可以为FastAPI提供一个类似结合Flask部署的专用接口
    
- 环境
- 复现代码或 repo 链接
- 复现步骤
- 其他信息
* **解决方案**

* **其他内容**

**Comment by whtsky** [comment]
我没有使用过 FastAPI ，欢迎有相关经验的人贡献 PR :)

**Comment by hanbaoqiu** [comment]
我也希望与Fastapi结合
顺便提一下,很多参考链接的网址都换了,例如下面的:
修改永久图文素材
详细请参考 http://mp.weixin.qq.com/wiki/10/c7bad9a463db20ff8ccefeedeef51f9e.html

**Comment by zongjingyao** [comment]
fastapi里可以通过`mount`把werobot挂载上去。

```python
import werobot
from fastapi import FastAPI
from fastapi.middleware.wsgi import WSGIMiddleware

robot = werobot.WeRoBot()
app = FastAPI()

app.mount("/robot", WSGIMiddleware(robot.wsgi))
```

可以参考下[Sub Applications - Mounts](https://fastapi.tiangolo.com/advanced/sub-applications/)

**Comment by hanbaoqiu** [comment]
> fastapi里可以通过`mount`把werobot挂载上去。
> 
> ```python
> import werobot
> from fastapi import FastAPI
> from fastapi.middleware.wsgi import WSGIMiddleware
> 
> robot = werobot.WeRoBot()
> app = FastAPI()
> 
> app.mount("/robot", WSGIMiddleware(robot.wsgi))
> ```
> 
> 可以参考下[Sub Applications - Mounts](https://fastapi.tiangolo.com/advanced/sub-applications/)

非常感谢
